 <!DOCTYPE html>
<!--[if gte IE 9]>
<html class="ie" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="ie-8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 7]>
<html class="ie-7" <?php language_attributes(); ?>>
<![endif]-->
<head>
	<!-- <meta charset="utf-8" /> -->
	<meta charset="<?php bloginfo( 'charset' ); ?>" />
	<meta name="viewport" content="width=device-width" />
	<title><?php wp_title ( "|",true, "right" ); ?></title>
	<link rel="profile" href="http://gmpg.org/xfn/11" />
	<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>" />
	<!--[if lt IE 9]>
		<link rel="stylesheet" href="<?php echo get_stylesheet_directory_uri(); ?>/css/ie7-8.css" type="text/css" media="screen, projection" />
	<![endif]-->
	<?php wp_head(); ?> 
</head>
<body <?php body_class(); ?>>
	<div class="wrapper"><!-- used to keep footer at the bottom of the browser window -->
		<div id="slider_wrapper"><?php
			global $reddish_slider_options;
			$slider_settings = get_option( 'reddish_slider_options', $reddish_slider_options );
			
			if ( is_single() && 1 == $slider_settings[ 'show_on_single_posts' ] ) {
				$reddish_post_meta_checkbox = get_post_meta( $post->ID, 'reddish_post_meta_checkbox', true ); // return saved value of meta box
				$reddish_post_meta_checkbox['slider_with_post'] = isset($reddish_post_meta_checkbox['slider_with_post'] )? $reddish_post_meta_checkbox['slider_with_post'] : ''; //if the values doesn't exists, use defaults
				if ( 1 == $slider_settings[ 'post_checked' ] && ( '' == $reddish_post_meta_checkbox['slider_with_post'] ) ) {
					reddish_slider_template();
				} elseif ( ( 2 == $slider_settings[ 'post_checked' ] ) && ( 'on' == $reddish_post_meta_checkbox['slider_with_post'] ) ) {
					reddish_slider_template();
				} elseif ( 3 == $slider_settings[ 'post_checked' ] ) {
					reddish_slider_template();
				}
			} elseif ( is_front_page() && ( 1 == $slider_settings[ 'show_on_front_page' ] ) ) {
				reddish_slider_template();
			} elseif ( is_page() && ! ( 0 == $slider_settings[ 'show_on_single_pages' ] ) ) {
				$reddish_post_meta_checkbox = get_post_meta( $post->ID, 'reddish_post_meta_checkbox', true ); // return saved value of meta box
				$reddish_post_meta_checkbox['slider_with_post'] = isset($reddish_post_meta_checkbox['slider_with_post'] )? $reddish_post_meta_checkbox['slider_with_post'] : ''; //if the values doesn't exists, use defaults
				if ( 1 == $slider_settings[ 'post_checked' ] && ( '' == $reddish_post_meta_checkbox['slider_with_post'] ) ) {
					reddish_slider_template();
				} elseif ( ( 2 == $slider_settings[ 'post_checked' ] ) && ( 'on' == $reddish_post_meta_checkbox['slider_with_post'] ) ) {
					reddish_slider_template();
				} elseif ( 3 == $slider_settings[ 'post_checked' ] ) {
					reddish_slider_template();
				}
			} elseif ( ( 1 == $slider_settings[ 'show_on_other_pages' ] ) && ( ! is_front_page() && ! is_single() && ! is_page() ) ) {
				reddish_slider_template();
			} ?>
		</div>
		<div id ="menu_wrapper">
			<div id="page_top" class="container">
					<?php reddish_display_bloginfo_name(); ?>
				<!-- display menu; if no menu is assigned to the location, function wp_page_menu is called. UL element created by this function has default class 'menu', so in order to use the same styles for menuus generated by these functions, 'menu' value is assigned to 'container_class'-->
				<?php wp_nav_menu( array( 'theme_location' => 'primary', 'container_class' => ' menu site-navigation main-navigation' ) ); ?>
				<div class="clear"></div>
			</div><!-- .container-->
			<div class="clear"></div>
		</div>
		<?php  
			if ( ! ('' == get_header_image() || false == get_header_image()) || ( 'blank' !== get_header_textcolor() ) ) :
			reddish_admin_header_image(); ?>
		<?php endif; ?>
		<div class="hdblock">
			<?php if ( ! is_404() ) : ?>
				<div class="container">
					<?php reddish_breadcrumbs(); ?>
					<div class="search_form right ">
						<?php get_search_form(); ?>
					</div><!-- .search_form -->
					<div class="clear"></div>
				</div><!-- .container-->
			<?php endif; ?><!-- ( ! is_404() -->
		</div><!-- hdblock -->
		<div class="clear"></div>
		<div class="container"><!-- start tag of the main-content block; end tag is in footer -->